### ISSUE TITLE
掉input[type="number"]右边的箭头

### ISSUE THREAD

**Issue by 5Mi** [5Mi/wumi_blog#34]
```scss
//去掉input[type="number"]右边的箭头
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    -webkit-appearance: none;
}
input[type="number"]{
    -moz-appearance: textfield;
}
```
