### ISSUE TITLE
px em和rem等

### ISSUE THREAD

**Issue by 5Mi** [5Mi/wumi_blog#9]
页面中body的默认font-size 一般为16px; 那么 1.4rem = (16 * 1.4 )px 

但一般我们使用“1em”等于“10px”来改变默认值“1em=16px”，这样一来，我们设置字体大小相当于“14px”时，只需要将其值设置为“1.4em”。所以需要设置
```css
body {
				font-size: 62.5%;/*10 ÷ 16 × 100% = 62.5%*/ /*font-size设为10px*/
			}
```
那么在sass中我们可以有如下mixin
```sass
//字体大小
@mixin fontSize($size:14){
    font-size:#{$size/10}rem;   /*默认1.4rem = 1.4 *10 px */
}
```
